parameters:
    stack_api_url: https://api.stackexchange.com
    stack_api_version: 2.2

services:
    kamde_stack_ext.client_factory:
        class: Kamde\StackExtBundle\Service\ClientFactory

    kamde_stack_ext.stack_client:
        class: GuzzleHttp\Client
        factory: 'kamde_stack_ext.client_factory:create'
        arguments:
            - []
            -
              base_uri: '%stack_api_url%/%stack_api_version%'
              headers:
                  User-Agent: 'Kamde StackExtBundle 0.1'
                  Accept: 'application/json'
                  content-type: 'application/json'
            - ~

    kamde_stack_ext.connector.stackoverflow:
        class: Kamde\StackExtBundle\Service\Connector\StackConnector
        arguments:
            - '@kamde_stack_ext.stack_client'
            - 'stackoverflow'

    kamde_stack_ext.resource_factory:
        class: Kamde\StackExtBundle\Service\Resource\ResourceFactory
        autowire: true