parameters:
    api_url: https://api.stackexchange.com
    api_version: 2.2

services:
    kamde_stack_ext.client_factory:
        class: Kamde\StackExtBundle\Service\ApiClient\ClientFactory

    kamde_stack_ext.stack_client:
        class: GuzzleHttp\Client
        factory: 'kamde_stack_ext.client_factory:create'
        arguments:
            - []
            -
              base_uri: '%api_url%/%api_version%'
              headers:
                  User-Agent: 'Kamde StackExtBundle 0.1'
                  Accept: 'application/json'
                  content-type: 'application/json'
            - ~

    kamde_stack_ext.connector.stackoverflow:
        class: Kamde\StackExtBundle\Service\ApiClient\Connector
        arguments:
            - '@kamde_stack_ext.stack_client'
        calls:
            - [setSite, ['stackoverflow']]
            
    kamde_stack_ext.resource_factory:
        class: Kamde\StackExtBundle\Service\ApiClient\Resource\ResourceFactory
        arguments:
            - '@kamde_stack_ext.connector.stackoverflow'